### ISSUE TITLE
1.21.1 Checklist:

### ISSUE THREAD

**Issue by muon-rw** [muon-rw/Medieval-Origins-Old#172]
- [x] Remove all Pehkui references in favor of vanilla/AEA attributes
- [x] Refactor enchantments, now data driven
- [x] Refactor to new Power/Action/Condition types
- [x] Remove multiloader support, clean up structure
- [x] Remove entity group references, refactor to type tag
- [x] Clean up and improve summons integration
- [x] Origins data structure changes (hooooh boy)
- [x] Replace all Apugli features
- [ ] Sounds are corrupted?
- [x] **Replace broken functions:** 
- [x] Arachnae Web Sling/extricate
- [x] Resource empowered attr for rev summons (Remember to heal, withers get boost and skeleton horses should get scale)
- [x] Pixie fake expl
- [x] Fae levitate
