### ISSUE TITLE
Multiloader project potential regressions checklist

### ISSUE THREAD

**Issue by muon-rw** [muon-rw/Medieval-Origins-Old#91]
- [ ] Projectile Damage on Summons
- [x] Recreate publishing scripts
- [x] Spell Power scaling powers -> Create Iron's alternative
- [x] Spell Power attributes bonuses -> use Iron's attributes
- [x] Cross-platform spell power lang issue
- [x] Remake mana powers + add RPGMana option
- [x] Create Owner Attribute Transfer on Forge
- [x] AutoTag / item conditions
- [x] Additional Entity Attributes Forge in-dev (crashes)
- [x] Refactor summon/owner implementation
- [x] Remake Icarus mixins
- [x] Apotheosis/Zenith specific empowered shot powers
- [x] double check power load conditions 
- note: can't properly have multiple load conditions... move into instance folders
- [x] Have all optional power compats:
- survive
- TAN
- thermoo patches
- environmentz
- dehydration
